FROM node:slim

ARG PLATE_RECOGNIZER_API_TOKEN
ARG API_HOST
ARG SNAPSHOT_FOLDER="./test"

ENV PLATE_RECOGNIZER_API_TOKEN=${PLATE_RECOGNIZER_API_TOKEN}
ENV API_HOST=${API_HOST}
ENV SNAPSHOT_FOLDER=${SNAPSHOT_FOLDER}

WORKDIR /app

COPY . .

RUN mkdir test
RUN npm i
RUN npm run build

CMD npm start