version: "3"

services:
  snapshotserver:
    build:
      context: ./snapshotserver
      dockerfile: ./snapshotserver.Dockerfile
      args:
        - INPUT_STREAM_FROM=${INPUT_STREAM}
    volumes:
      - snapshotlocation:/src

  filesender:
    build:
      context: ./filesender
      dockerfile: ./filesender.Dockerfile
      args:
        - API_TOKEN=${PLATE_RECOGNIZER_API_TOKEN}
        - SNAPSHOT_FOLDER=${FOLDER}
    volumes:
      - snapshotlocation:/app/test

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db:/db

  condomanager:
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_CONNECTION_STRING: $DB_CONNECTION_STRING
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
    build:
      context: ./condomanager
      dockerfile: ./bin/condomanager.Dockerfile
    ports:
      - "8080:8080"
    links:
      - mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://condomanager:8080/actuator/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  condoclient:
    depends_on:
      condomanager:
        condition: service_healthy
    build:
      context: ./condoclient
      dockerfile: ./bin/condoclient.Dockerfile
    ports:
      - "8094:80"
    links:
      - condomanager

volumes:
  snapshotlocation:
